# file: config-new.yaml
#
# This configuration file was created by Gregor von Laszewski laszewski@gmail.com
# The values under image: and some other values have been taken from
#
# SciML-Bench, which is under
#   Copyright Â© 2022 Scientific Machine Learning Research Group
#   Scientific Computing Department, Rutherford Appleton Laboratory
#   Science and Technology Facilities Council, UK.
#   All rights reserved.
#
# Several values of that have been modified also by
#    Gregor von Laszewski, Juri Papay
#
# This is a configuration file for the MLcommons Science CloudMask benchmark.
# It works with cloudmask_v2.py

name: cloudmask-rivanna

sbatch:
  mode: h
  dir: scratch

run:
  fit-verbose: 1
  host: rivanna
  target: rivanna-singularity
  filesystem: "/scratch/thf2bn"
  venvpath: "/scratch/thf2bn/ENV3/bin/python"
  datadir: data
  branch: 'main'

# Submission Information
submission:
  name: cloudmask
  submitter: Gregor von Laszewski
  email: laszewski@gmail.com
  org: University of Virginia
  division: open
  version: mlcommons-cloudmask-v2.0
  github_commit_version: TBD
  status: completed
  platform: rivanna
  accelerators_per_node: 1

experiment:
#  card_name: a100
  card_name: a100
  gpu_count: 1
  cpu_num: 1
  mem: "64GB"
  repeat: "1"
  epoch: "1"
  seed: 1234
  learning_rate: 0.001
  batch_size: 32
  train_split: 0.8
  clip_offset: 15
  no_cache: False
  nodes: 1
  gpu: 1

system:
  host: "rivanna"
  python: "3.10.8"
  num_cpus: 1
  partition: "bii-gpu"
  allocation: bii_dsc_community
  platform: rivanna
  accelerators_per_node: 1
  constraint: ""
  reservation: ""

#  allocation: bii_dsc_community
#  reservation: bi_fox_dgx

mask: "float"

training:
  loss: binary_crossentropy
  metrics: accuracy

data:
  scratch: "/project/bii_dsc_community/thf2bn/data/cloudmask"
  training: "{data.scratch}/one-day"
  inference: "{data.scratch}/ssts"
  model: "{data.output}/cloudModel.h5"
  output: "./outputs"

log:
  file: "{data.output}/c_cloudmask_run.log"
  mlperf: "{data.output}/c_mlperf_cloudmask.log"

image:
  # Size of each patch to feed to the network
  PATCH_SIZE: 256
  # Original height of the image
  IMAGE_H: 1200
  # Original width of the image
  IMAGE_W: 1500
  # No. of channels
  N_CHANNELS: 9
  # Min allowable SST
  MIN_SST: 273.15
  # Amount to crop the edges of the images by
  CROP_SIZE: 80

#